### PR TITLE
Readme Update - adds setup & contribution instructions, and current sprint goals

### LINKED ISSUE #2: reformat README

### PR DESCRIPTION
**Pull request by razzlepdx**
Resolves #2.

Hello everyone, this is just a quick change to the README.  I wanted to update it with the goals for our current sprint, and also thought that documenting some setup and contribution processes might be a good idea. 

If there are any steps I missed, or anything that's unclear, feel free to comment or make changes to the readme-edit branch yourself!

### CODE REVIEW

**Comment by razzlepdx** [comment]
You can see the properly formatted view of my edits here: https://github.com/Improbable-Astronauts/octo-carnival/blob/4fa431da3a7f2ce63e10751f2bf35e918fe5628c/README.md

**Review by danphill01 — CHANGES_REQUESTED** [review]
Remove mvpvenv from the repo .gitignore.
Remove pytz from requirements.txt (it will be installed with Django)
Move selenium from requirements.txt to test_requirements.txt. (not a requirement for running the app, only for testing)
We might want to talk about the migrate step. If we make sure that we include a proper db.sqlite3 file, the we wouldn't need it. If the user is using a different DB configuration, then they would need to configure it in settings before doing the migrate anyway.

**Comment by razzlepdx** [comment]
Thanks, Dan!  I have a couple of questions about these:

Remove mvpvenv from the repo .gitignore. 
- this is my virtual environment, isn't that supposed to be ignored?  Or should that file just stay untracked throughout the project?

Remove pytz from requirements.txt (it will be installed with Django)
Move selenium from requirements.txt to test_requirements.txt. (not a requirement for running the app, only for testing)
- for the 2 above, I was following the practice of running 'pip freeze > requirements.txt' to make sure no requirements were missing.  I can see why you would add a test_requirements.txt and to move selenium there, but is there harm in having pytz listed, since it will ultimately be part of your dev environment anyway?

**Comment by danphill01** [comment]
yes, mvpvenv is your virtualenv but we have a step that explicitly tells the person setting up the server to add their virtual env name to the .gitignore. Therefore yours shouldn't be there for everybody! Your virtual env name should only be in your local .gitignore. 
Probably no harm in leaving pytz because it will always be a dependency for Django, but it isn't _our_ requirement. `pip freeze` is nice but we can also just add modules that we know we need to keep requirements.txt small and clean. When it comes time to update versions, the maintainer will have to sort through all the lines in requirements.txt to verify which we are still using and what version they need to be.

**Pull request merged**
