### PR TITLE
Removes list view

### PR DESCRIPTION
**Pull request by razzlepdx**
Hi all - I have made a few small changes to the master branch here - I realized that since our goal for this week was to display all movies on the main view template, my branch was getting a bit ahead of itself.  For now I've commented out the code related to list views, and we can reimplement it if and when we get to that step.

### CODE REVIEW

**Comment by razzlepdx** [comment]
I went ahead and deleted those code blocks for now, since commenting so much out probably just makes things more confusing :)

**Comment by JasonOnes** [comment]
Sounds and looks good to me.

**Review by danphill01 — APPROVED** [review]

**Review by JasonOnes — APPROVED** [review]
Okay I found it, duh.

**Comment by razzlepdx** [comment]
Thank you both for taking a look! @danphill01 @JasonOnes

**Pull request merged**
